#!/usr/bin/env bash

# Check for correct number of arguments
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Extract arguments
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer the file using scp
scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip:~/"

if [ $? -eq 0 ]
then
	echo "File transferred successfully."
else
	echo "File transfer failed"
fi

